const quotes = [
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best way to predict the future is to invent it.",
    "Believe you can and you're halfway there.",
    "You miss 100% of the shots you don't take.",
    "The journey of a thousand miles begins with one step.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only person you are destined to become is the person you decide to be.",
    "Don't watch the clock; do what it does. Keep going.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "Your time is limited, don't waste it living someone else's life.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The harder I work, the luckier I get.",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
    "The only place where success comes before work is in the dictionary.",
    "The secret of getting ahead is getting started.",
    "Don't count the days, make the days count.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Your time is limited, don't waste it living someone else's life.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The harder I work, the luckier I get.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "The only place where success comes before work is in the dictionary.",
  "The secret of getting ahead is getting started.",
  "Don't count the days, make the days count.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "If you want to achieve greatness, stop asking for permission.",
  "If you want to achieve greatness, stop asking for permission.",

  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "Don't watch the clock; do what it does. Keep going.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Your time is limited, don't waste it living someone else's life.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The harder I work, the luckier I get.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "The only place where success comes before work is in the dictionary.",
  "The secret of getting ahead is getting started.",
  "Don't count the days, make the days count.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "If you want to achieve greatness, stop asking for permission.",
  "If you want to achieve greatness, stop asking for permission.",

  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "Don't watch the clock; do what it does. Keep going.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The best way to predict the future is to create it.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "The successful warrior is the average man, with laser-like focus.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only person you are destined to become is the person you decide to be.",
  "If you're going through hell, keep going.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "In the end, we only regret the chances we didn't take.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Your time is limited, don't waste it living someone else's life.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The harder I work, the luckier I get.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "The only place where success comes before work is in the dictionary.",
  "The secret of getting ahead is getting started.",
  "Don't count the days, make the days count.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not in what you have, but who you are.",
  "Don't compare your beginning to someone else's middle.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't be afraid to give up the good to go for the great.",
  "You can't change what's going on around you until you start changing what's going on within you.",
  "Don't wait. The time will never be just right.",
  "Your time is limited, don't waste it living someone else's life.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Don't be afraid of failure. Be afraid of not trying.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Your time is limited, don't waste it living someone else's life.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The harder I work, the luckier I get.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "The only place where success comes before work is in the dictionary.",
  "The secret of getting ahead is getting started.",
  "Don't count the days, make the days count.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Don't be afraid of failure. Be afraid of not trying.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Your time is limited, don't waste it living someone else's life.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The harder I work, the luckier I get.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "The only place where success comes before work is in the dictionary.",
  "The secret of getting ahead is getting started.",
  "Don't count the days, make the days count.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The only way to achieve the impossible is to believe it is possible.",
  "The only time you should ever look back is to see how far you've come.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only person you are destined to become is the person you decide to be.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to do great work is to love what you do.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "In the end, we only regret the chances we didn't take.",
  "If you want to achieve greatness, stop asking for permission.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "If you're going through hell, keep going.",
  "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The successful warrior is the average man, with laser-like focus.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
  "Every strike brings me closer to the next home run.",
  "Life is not about finding yourself. It's about creating yourself.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  ];
  
  // Rest of the code remains the same
  
  
const quoteElement = document.getElementById("quote");
const generateBtn = document.getElementById("generate-btn");
const copyBtn = document.getElementById("copy-btn");

generateBtn.addEventListener("click", generateQuote);
quoteElement.addEventListener("click", copyQuote);

function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const randomQuote = quotes[randomIndex];
  quoteElement.textContent = randomQuote;
  copyBtn.classList.add("hidden");
}

function copyQuote() {
  const range = document.createRange();
  range.selectNode(quoteElement);
  window.getSelection().removeAllRanges();
  window.getSelection().addRange(range);
  document.execCommand("copy");
  window.getSelection().removeAllRanges();

  copyBtn.textContent = "Copied!";
  copyBtn.classList.add("show");
  quoteElement.classList.add("copied");

  setTimeout(() => {
    copyBtn.textContent = "Copy Quote";
    copyBtn.classList.remove("show");
    quoteElement.classList.remove("copied");
  }, 2000);
}
  